HabitHive/front-react

- src/components/common/Header.jsx
- src/components/common/Layout.jsx
- src/components/common/Navbar.jsx
- src/pages/LogInPage.jsx
- src/pages/MainDailyPage.jsx
- src/pages/NotFoundPage.jsx
- src/pages/SignUpPage.jsx
- src/shared/Router.jsx
> Header, Navbar 구현

- package.json
- src/components/main/daily/WeekCalendar.jsx
- yarn.lock
> #19 daily 날짜 표시하기

- src/components/login/LoginForm.jsx
> #22 LoginPage css 수정

- src/components/common/SubmitBtn.jsx
- src/components/login/LoginForm.jsx
- src/components/signup/SignupForm.jsx
- src/components/survey/Category.jsx
- src/components/survey/categories.js
- src/pages/SurveyPage.jsx
> #24 관심사 페이지 구현

- package.json
- src/components/main/monthly/MonthlyCalendar.jsx
- src/pages/MonthlyPage.jsx
- src/shared/Router.jsx
- yarn.lock
> #30 캘린더 구현하기

- src/pages/PostingPage.jsx
> #32 postPage 뷰

- src/axios/axios.js
- src/components/login/LoginForm.jsx
- src/components/signup/SignupForm.jsx
- src/components/survey/Category.jsx
- src/components/survey/CategoryBtn.jsx
- src/components/survey/categories.js
- src/pages/OnboardingPage.jsx
- src/shared/Router.jsx
> surveyPage 기능구현 완료

- src/axios/axios.js
- src/axios/setToken.js
- src/components/common/Navbar.jsx
- src/components/login/LoginForm.jsx
- src/components/mypage/Profile.jsx
- src/components/mypage/UserTags.jsx
- src/components/signup/SignupForm.jsx
- src/index.js
- src/pages/MyPage.jsx
- src/pages/SurveyPage.jsx
- src/redux/modules/user.js
- src/redux/store/configStore.js
마이페이지 기능 구현 작업 중
로그인 (인증인가) 기능 수정 중
> #40 MyPage UserInfo 기능 구현 완료

- src/components/common/Loading.jsx
- src/components/mypage/TagWeekday.jsx
- src/components/mypage/ToggleTags.jsx
- src/components/mypage/UserTags.jsx
> myPage 기능 구현 완료

- src/components/common/SaveButton.jsx
- src/components/main/monthly/MonthlyCalendar.jsx
- src/pages/PostingPage.jsx
> #32 포스트페이지 St및 공용 저장버튼 컴포넌트 생성

- src/components/main/daily/WeekCalendar.jsx
- src/components/post/PostForm.jsx
- src/pages/MainDailyPage.jsx
> #19 일별 위클리바

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/WeekCalendar.jsx
- src/pages/MainDailyPage.jsx
> #64 일별 습관리스트 구현

- src/components/main/daily/MyTag.jsx
- src/pages/MainDailyPage.jsx
> #68 dailyPage 나의 습관리스트 구현

- src/components/common/Navbar.jsx
- src/components/mypage/SubNav.jsx
- src/components/mypage/UserTags.jsx
- src/redux/modules/tagbuy.js
- src/redux/modules/user.js
로컬 스토리지 토큰 삭제 추가
navigate 추가 작업 필요
> 로그아웃 기능 구현

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/MyTag.jsx
- src/pages/MainDailyPage.jsx
- src/redux/modules/mytag.js
- src/redux/store/configStore.js
> #69 나의 습관리스트 데이터받아오기

- src/components/main/daily/MyTag.jsx
- src/components/main/monthly/MonthlyCalendar.jsx
- src/components/post/PostForm.jsx
- src/redux/modules/mytag.js
- src/redux/modules/post.js
- src/redux/store/configStore.js
> #32 post api 추가

- src/components/post/PostForm.jsx
> #32  post api(2)

- src/components/common/Alert.jsx
- src/components/signup/SignupForm.jsx
- src/components/survey/Category.jsx
- src/redux/modules/mypage.js
- src/redux/modules/user.js
> #70 #76 로그인 회원가입 예외처리

- src/components/main/daily/MyTag.jsx
- src/components/main/daily/WeekCalendar.jsx
- src/components/post/PostForm.jsx
- src/redux/modules/mytag.js
> #32 습관 데이터 받아오기

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/WeekCalendar.jsx
- src/components/post/RepeatDay.jsx
- src/pages/MainDailyPage.jsx
- src/redux/modules/dailytag.js
- src/redux/modules/mytag.js
> #64 post 성공 후 일별습관리스트 구현

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/MyTag.jsx
- src/components/main/daily/WeekCalendar.jsx
- src/components/post/RepeatDay.jsx
- src/pages/MainDailyPage.jsx
- src/redux/modules/dailytag.js
- src/redux/modules/post.js
- src/redux/store/configStore.js
> #68 나의 습관 데이터 리스트 받아오기

- src/components/main/daily/DailyTag.jsx
- src/redux/modules/tagbuy.js
> #64 오늘의 습관리스트 read 구현

- src/components/main/daily/DailyTag.jsx
> #64 체크박스 상태관리

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/TodayTagList.jsx
- src/redux/modules/dailytag.js
> #64 checkbox redux

- src/components/main/daily/MyTag.jsx
- src/pages/MainDailyPage.jsx
> #108 modal 구현

- src/components/main/daily/WeekCalendar.jsx
- src/redux/modules/dailytag.js
> #19 weekbar daylist수정

- src/pages/MainDailyPage.jsx
> testcode삭제

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/WeekCalendar.jsx
- src/components/main/monthly/MonthlyCalendar.jsx
- src/redux/modules/dailytag.js
- src/redux/modules/month.js
데일리페이지 최초 진입시 오늘 날짜, 그다음 클릭한 날짜로 습관목록 구현
> #64 데일리페이지 최초 진입시 오늘 날짜, 그다음 클릭한 날짜로 습관목록 구현

- src/components/main/daily/DailyTag.jsx
- src/components/post/PostForm.jsx
- src/edit/EditForm.jsx
- src/edit/EditRepeat.jsx
- src/redux/modules/schedule.js
- src/redux/store/configStore.js
> #126 등록된 일정 삭제하기

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/MyTag.jsx
- src/components/post/PostForm.jsx
- src/edit/EditForm.jsx
- src/edit/EditRepeat.jsx
- src/redux/modules/schedule.js
> #124 edit기능 추가

- src/edit/EditForm.jsx
> #124 128번커밋누락본 추가

- src/edit/EditForm.jsx
- src/edit/EditRepeat.jsx
> #49 체크했던 요일정보 받아오기/checked 구현

- src/components/main/daily/WeekCalendar.jsx
- src/pages/MainDailyPage.jsx
> #131 weekbar css

- src/components/main/daily/TodayTagList.jsx
- src/redux/modules/dailytag.js
> #131 dailyTag 완료시 CSS 변경

- src/components/main/daily/TodayTagList.jsx
- src/components/main/daily/WeekCalendar.jsx
- src/components/main/monthly/MonthlyCalendar.jsx
- src/pages/MonthlyPage.jsx
- src/redux/modules/dailytag.js
> #139 습관 완료시 sweetalert추가

- src/App.js
- src/components/login/LoginForm.jsx
- src/components/mypage/SubNav.jsx
- src/redux/modules/user.js
- src/shared/Router.jsx
> 로그인 로그아웃 로직 수정

- src/components/post/PostForm.jsx
- src/redux/modules/schedule.js
> #151 구매한 습관 일정등록하기

- src/components/main/monthly/MonthlyCalendar.jsx
> #154 클릭시 날짜별 목표습관리스트 가져오기

- src/components/post/PostForm.jsx
이미 첫 등록 이후에 추가 등록시라면, 첫 등록시의 endDate 를 그대로 고정
> #151 이미 첫 등록 이후에 추가 등록시라면, 첫 등록시의 endDate 를 그대로 고정

- src/components/post/PostForm.jsx
> #151 첫 등록 시에도 endDate가 고정되어버리는 로직 수정

- src/components/main/daily/DailyTag.jsx
- src/components/main/monthly/Calendar.css
- src/components/main/monthly/MonthlyCalendar.jsx
- src/pages/MonthlyPage.jsx
- src/redux/modules/dailytag.js
- src/redux/modules/month.js
먼슬리페이지 새로고침 시 undefined로 오류나는 것 수정
> #154 먼슬리페이지 새로고침 시 undefined로 오류나는 것 수정

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/MyTag.jsx
- src/pages/MainDailyPage.jsx
- src/redux/modules/dailytag.js
> #131 배포용 css 수정

- src/components/main/daily/WeekCalendar.jsx
- src/pages/MonthlyPage.jsx
> #131 weekbar 날짜 클릭시 클릭한 날짜 색 바꾸기

- src/components/main/daily/TodayTagList.jsx
- src/components/main/monthly/Calendar.css
> #131 일자별 습관리스트 색상 구현

- src/components/tagbuy/TagBuyDrawer.jsx
> #171 에러 수정

- src/components/common/SaveButton.jsx
- src/components/main/daily/WeekCalendar.jsx
- src/components/post/PostForm.jsx
- src/components/post/RepeatDay.jsx
- src/edit/EditForm.jsx
- src/edit/EditRepeat.jsx
- src/pages/MainDailyPage.jsx
> #131 main, post,edit 페이지 css 수정

- src/components/main/daily/MyTag.jsx
- src/components/main/daily/TodayTagList.jsx
- src/pages/MainDailyPage.jsx
> #131 mytag css 수정

- src/components/main/daily/TodayTagList.jsx
- src/edit/EditForm.jsx
- src/redux/modules/schedule.js
완료된 습관 수정불가 및 미완료 습관 수정 시 placeholder삭제하고 등록했던 데이터를 초기값으로 넣어줌
> #124 완료된 습관 수정불가 및 미완료 습관 수정 시 placeholder삭제하고 등록했던 데이터를 초기값으로 넣어줌

- src/components/main/daily/MyTag.jsx
- src/pages/MainDailyPage.jsx
layout수정에 따른 css width 수정(나의 습관목록)
> #131 layout수정에 따른 css width 수정(나의 습관목록)

- src/components/post/PostForm.jsx
post시 날짜,시간,요일 중 하나라도 null이면 에러메시지 및 post불가
> #151 post시 날짜,시간,요일 중 하나라도 null이면 에러메시지 및 post불가

- public/index.html
- src/axios/axios.js
- src/components/common/GlobalStyle.jsx
- src/components/pet/Pet.jsx
- src/components/pet/petData.js
- src/redux/modules/tagbuy.js
> #159 petPage 게이미피케이션 추가

- src/redux/modules/pet.js
> #159 에러 수정

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/TodayTagList.jsx
> #131 dailyPage - tagList 디자인 변경

- src/components/main/daily/DailyTag.jsx
- src/pages/MainDailyPage.jsx
> #131 dailyPage 일별목표,목표없을 때 글자크기 수정

- src/components/main/daily/WeekCalendar.jsx
- src/pages/MainDailyPage.jsx
dialy Header 뿌연 이미지 수정 및 사이즈 재확인
> #131 dialy Header 뿌연 이미지 수정 및 사이즈 재확인

- src/components/main/daily/TodayTagList.jsx
- src/components/post/PostForm.jsx
- src/edit/EditForm.jsx
> #131 customAlert 수정

- src/components/main/daily/WeekCalendar.jsx
- src/components/post/PostForm.jsx
- src/pages/MainDailyPage.jsx
today는 배경색다르게 표현, 클릭한 날짜는 다른 배경색으로 표현
> #131 today는 배경색다르게 표현, 클릭한 날짜는 다른 배경색으로 표현

- src/components/common/GlobalStyle.jsx
- src/components/common/MobileLayout.jsx
- src/index.js
> #222 mobile layout 개선

- src/edit/EditForm.jsx
등록된 일정 수정시 endDate가 1일이 더 들어가는것 수정
> #131 등록된 일정 수정시 endDate가 1일이 더 들어가는것 수정

- src/components/post/PostForm.jsx
> #131 postPage 에 태그박스 css 수정

- src/components/post/PostForm.jsx
> #131 에러텍스트 css 수정

- src/components/post/PostForm.jsx
- src/edit/EditForm.jsx
postPage 버튼, edit 태그css와 버튼 css
> #131 postPage 버튼, edit 태그css와 버튼 css

- src/edit/EditForm.jsx
- src/pages/MonthlyPage.jsx
> #131 monthly 캘린더 밑 일별목표 위치 수정

- src/components/common/Navbar.jsx
- src/components/mypage/UserTags.jsx
- src/components/pet/Pet.jsx
- src/components/tagbuy/TagBuyDrawer.jsx
- src/redux/modules/tagbuy.js
> CSS 및 예외 처리 추가

- src/components/main/daily/DailyTag.jsx
- src/components/main/daily/TodayTagList.jsx
- src/pages/MainDailyPage.jsx
- src/pages/MonthlyPage.jsx
monthly페이지에서는 나의 일별 목표의 습관수정/삭제/완료 불가
> #237 monthly페이지에서는 나의 일별 목표의 습관수정/삭제/완료 불가

- src/components/main/monthly/MonthlyCalendar.jsx
- src/components/main/monthly/react-datepicker.css
> #30 캘린더 코드 리팩토링

- src/components/main/monthly/MonthlyCalendar.jsx
> #30 캘린더 날짜구하기 함수식 정리

- src/components/main/monthly/MonthlyCalendar.jsx
> #30 코드 리팩토링

- src/pages/MonthlyPage.jsx
- src/redux/modules/dailytag.js
> #237 일별목표 밑 색상 잘리는 부분 수정

- src/components/main/daily/TodayTagList.jsx
- src/components/main/daily/WeekCalendar.jsx
- src/redux/modules/dailytag.js
> #237 미래날짜 습관 done불가

- src/components/main/daily/TodayTagList.jsx
- src/redux/modules/dailytag.js
> #237 오늘이 아닌 일정에 대한 알람
